hsv_h: "0.015"
hsv_s: "0.5"
hsv_v: "0.4"

degrees: "5.0"
translate: "0.05"
scale: "0.3"
shear: "0.0"
perspective: "0.0"

fliplr: "0.5"
flipud: "0.0"

mosaic: "0.5"
mixup: "0.0"
copy_paste: "0.0"

close_mosaic: "10"
